[package]
name = "lf-pico"
version = "0.1.0"

[[app]]
target = "C"
platform = "Pico"
main_reactor = "./src/HelloPico.lf"

[app.dependencies]
# add a sdk path property
# provide the cmake with a configuration
# TODO

[app.properties]
